function grad_tpbvp_ode = autogen_grad_tpbvp_ode(I_pend,Q_swingup1_1,Q_swingup1_2,Q_swingup1_3,Q_swingup1_4,Q_swingup2_1,Q_swingup2_2,Q_swingup2_3,Q_swingup2_4,Q_swingup3_1,Q_swingup3_2,Q_swingup3_3,Q_swingup3_4,Q_swingup4_1,Q_swingup4_2,Q_swingup4_3,Q_swingup4_4,R_swingup1,b1,b2,dtheta_pend,dx_cart,g,lambda3,lambda4,m_cart,m_pend,r_com_pend,theta_pend)
%AUTOGEN_GRAD_TPBVP_ODE
%    GRAD_TPBVP_ODE = AUTOGEN_GRAD_TPBVP_ODE(I_PEND,Q_SWINGUP1_1,Q_SWINGUP1_2,Q_SWINGUP1_3,Q_SWINGUP1_4,Q_SWINGUP2_1,Q_SWINGUP2_2,Q_SWINGUP2_3,Q_SWINGUP2_4,Q_SWINGUP3_1,Q_SWINGUP3_2,Q_SWINGUP3_3,Q_SWINGUP3_4,Q_SWINGUP4_1,Q_SWINGUP4_2,Q_SWINGUP4_3,Q_SWINGUP4_4,R_SWINGUP1,B1,B2,DTHETA_PEND,DX_CART,G,LAMBDA3,LAMBDA4,M_CART,M_PEND,R_COM_PEND,THETA_PEND)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Apr-2020 17:31:39

% Q =
% [ Q1_1, Q1_2, Q1_3, Q1_4]
% [ Q2_1, Q2_2, Q2_3, Q2_4]
% [ Q3_1, Q3_2, Q3_3, Q3_4]
% [ Q4_1, Q4_2, Q4_3, Q4_4]

t2 = r_com_pend.^2;
t3 = cos(theta_pend);
t4 = m_pend.^2;
t5 = t3.^2;
t6 = sin(theta_pend);
t7 = dtheta_pend.^2;
t8 = I_pend.*m_cart;
t9 = I_pend.*m_pend;
t10 = m_cart.*m_pend.*t2;
t11 = t6.^2;
t12 = 1.0./R_swingup1;
t13 = t2.*t4;
t16 = t2.*t4.*t11;
t14 = t8+t9+t10+t13-t16;
t15 = 1.0./t14;
t17 = I_pend.*lambda3;
t18 = lambda3.*m_pend.*t2;
t19 = lambda4.*m_pend.*r_com_pend.*t6;
t20 = t17+t18+t19;
t21 = 1.0./t14.^2;
t22 = t2.*t4.*t5;
t23 = t8+t9+t10+t22;
t24 = 1.0./t23;
t25 = m_pend.*t2;
t26 = I_pend+t25;
t27 = 1.0./t23.^2;
t28 = Q_swingup1_2.*(-1.0./2.0)-Q_swingup2_1./2.0;
t29 = b2.*dtheta_pend.*m_cart;
t30 = b2.*dtheta_pend.*m_pend;
t31 = g.*r_com_pend.*t3.*t4;
t32 = g.*m_cart.*m_pend.*r_com_pend.*t3;
t33 = b1.*dx_cart.*m_pend.*r_com_pend.*t6;
t38 = t2.*t3.*t4.*t6.*t7.*2.0;
t34 = t29+t30+t31+t32+t33-t38;
t35 = t2.*t4.*t7.*t11.*2.0;
t36 = b1.*dx_cart.*m_pend.*r_com_pend.*t3;
t37 = t2.^2;
t39 = 1.0./t14.^3;
t40 = t4.^2;
t41 = I_pend.*b1.*dx_cart;
t42 = b1.*dx_cart.*m_pend.*t2;
t43 = g.*t2.*t3.*t4.*t6;
t44 = b2.*dtheta_pend.*m_pend.*r_com_pend.*t6;
t53 = r_com_pend.*t2.*t3.*t4.*t7.*2.0;
t54 = I_pend.*m_pend.*r_com_pend.*t3.*t7.*2.0;
t45 = t41+t42+t43+t44-t53-t54;
t46 = g.*t2.*t4.*t5;
t47 = r_com_pend.*t2.*t4.*t6.*t7.*2.0;
t48 = I_pend.*m_pend.*r_com_pend.*t6.*t7.*2.0;
t49 = b2.*dtheta_pend.*m_pend.*r_com_pend.*t3;
t50 = t5.*2.0;
t51 = t50-1.0;
t52 = 1.0./t23.^3;
t55 = 1.0./t14.^4;
t56 = I_pend.*b1;
t57 = b1.*m_pend.*t2;
t58 = t56+t57;
t59 = dtheta_pend.*r_com_pend.*t2.*t3.*t4.*4.0;
t60 = I_pend.*dtheta_pend.*m_pend.*r_com_pend.*t3.*4.0;
t61 = t59+t60-b2.*m_pend.*r_com_pend.*t6;
t62 = b2.*m_cart;
t63 = b2.*m_pend;
t64 = t62+t63-dtheta_pend.*t2.*t3.*t4.*t6.*4.0;
t65 = I_pend.*t6.*t7.*2.0;
t66 = b2.*dtheta_pend.*t3;
t67 = m_pend.*t2.*t6.*t7.*2.0;
t68 = g.*m_pend.*r_com_pend.*t51;
t69 = t65+t66+t67+t68;
t70 = g.*m_cart.*t6;
t71 = g.*m_pend.*t6;
t72 = m_pend.*r_com_pend.*t7.*t51.*2.0;
t73 = t70+t71+t72-b1.*dx_cart.*t3;
t74 = Q_swingup1_3.*(-1.0./2.0)-Q_swingup3_1./2.0;
t75 = Q_swingup1_4.*(-1.0./2.0)-Q_swingup4_1./2.0;
t76 = b2.*t3;
t77 = I_pend.*dtheta_pend.*t6.*4.0;
t78 = dtheta_pend.*m_pend.*t2.*t6.*4.0;
t79 = t76+t77+t78;
t80 = theta_pend.*2.0;
t81 = Q_swingup3_4.*(-1.0./2.0)-Q_swingup4_3./2.0;
t82 = sin(t80);
t83 = I_pend.*dtheta_pend.*t3.*4.0;
t84 = dtheta_pend.*m_pend.*t2.*t3.*4.0;
t85 = t83+t84-b2.*t6;
t86 = t62+t63-dtheta_pend.*t2.*t4.*t82.*2.0;
grad_tpbvp_ode = reshape([0.0,0.0,0.0,0.0,-Q_swingup1_1,t28,t74,t75,0.0,0.0,-t24.*(t46+t47+t48+t49-g.*t2.*t4.*t11+I_pend.*lambda4.*m_pend.*r_com_pend.*t3.*t12.*t15+lambda4.*r_com_pend.*t2.*t3.*t4.*t12.*t15+I_pend.*t2.*t3.*t4.*t6.*t12.*t20.*t21.*2.0+m_pend.*t3.*t4.*t6.*t12.*t20.*t21.*t37.*2.0)-t2.*t3.*t4.*t6.*t27.*(t41+t42+t43+t44+I_pend.*t12.*t15.*t20-I_pend.*m_pend.*r_com_pend.*t3.*t7.*2.0+m_pend.*t2.*t12.*t15.*t20-r_com_pend.*t2.*t3.*t4.*t7.*2.0).*2.0,-t24.*(t35+t36-g.*r_com_pend.*t4.*t6-t2.*t4.*t5.*t7.*2.0-g.*m_cart.*m_pend.*r_com_pend.*t6+m_pend.*r_com_pend.*t3.*t12.*t15.*t20+lambda4.*t2.*t3.*t4.*t6.*t12.*t15+m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t12.*t20.*t21.*2.0)-t2.*t3.*t4.*t6.*t27.*(t29+t30+t31+t32+t33-t2.*t3.*t4.*t6.*t7.*2.0+m_pend.*r_com_pend.*t6.*t12.*t15.*t20).*2.0,t28,-Q_swingup2_2+lambda3.*(m_pend.*r_com_pend.*t24.*(I_pend.*t3.*t7.*2.0-b2.*dtheta_pend.*t6+m_pend.*t2.*t3.*t7.*2.0-g.*m_pend.*r_com_pend.*t3.*t6.*4.0)+t2.*t4.*t5.*t27.*t45.*2.0-t2.*t4.*t11.*t27.*t45.*2.0+t5.*t11.*t37.*t40.*t45.*t52.*8.0+t2.*t3.*t4.*t6.*t27.*(t46+t47+t48+t49-g.*t2.*t4.*t11).*2.0+t2.*t4.*t5.*t12.*t20.*t26.*t39.*2.0-t2.*t4.*t11.*t12.*t20.*t26.*t39.*2.0+m_pend.*r_com_pend.*t2.*t3.*t4.*t6.*t27.*t69.*2.0+t5.*t11.*t12.*t20.*t26.*t37.*t40.*t55.*1.2e1+lambda4.*m_pend.*r_com_pend.*t2.*t4.*t5.*t6.*t12.*t26.*t39.*2.0)+lambda4.*(-m_pend.*r_com_pend.*t24.*(b1.*dx_cart.*t6+g.*m_cart.*t3+g.*m_pend.*t3-m_pend.*r_com_pend.*t3.*t6.*t7.*8.0)+t2.*t4.*t5.*t27.*t34.*2.0-t2.*t4.*t11.*t27.*t34.*2.0+t5.*t11.*t34.*t37.*t40.*t52.*8.0-t2.*t3.*t4.*t6.*t27.*(-t35-t36+g.*r_com_pend.*t4.*t6+t2.*t4.*t5.*t7.*2.0+g.*m_cart.*m_pend.*r_com_pend.*t6).*2.0-m_pend.*r_com_pend.*t6.*t12.*t15.*t20.*t24+lambda4.*t2.*t4.*t5.*t12.*t15.*t24+lambda4.*t5.*t11.*t12.*t37.*t39.*t40.*2.0-m_pend.*r_com_pend.*t2.*t3.*t4.*t6.*t27.*t73.*2.0+m_pend.*r_com_pend.*t2.*t4.*t5.*t6.*t12.*t20.*t39.*4.0-m_pend.*r_com_pend.*t2.*t4.*t6.*t11.*t12.*t20.*t39.*2.0+m_pend.*r_com_pend.*t2.*t4.*t5.*t6.*t12.*t15.*t20.*t27.*2.0+m_pend.*r_com_pend.*t2.*t4.*t5.*t6.*t12.*t20.*t21.*t24.*2.0+m_pend.*r_com_pend.*t5.*t6.*t11.*t12.*t20.*t37.*t40.*t55.*1.2e1),Q_swingup2_3.*(-1.0./2.0)-Q_swingup3_2./2.0+b1.*lambda4.*m_pend.*r_com_pend.*t3.*t24+b1.*lambda3.*t2.*t3.*t4.*t6.*t26.*t27.*2.0+b1.*lambda4.*m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t27.*2.0,Q_swingup2_4.*(-1.0./2.0)-Q_swingup4_2./2.0+lambda3.*m_pend.*r_com_pend.*t24.*t79-dtheta_pend.*lambda4.*t2.*t4.*t24.*cos(t80).*4.0+lambda4.*t2.*t3.*t4.*t6.*t27.*t86.*2.0-lambda3.*m_pend.*r_com_pend.*t2.*t3.*t4.*t6.*t27.*t85.*2.0,1.0,0.0,-t24.*t58,-b1.*m_pend.*r_com_pend.*t6.*t24,t74,Q_swingup2_3.*(-1.0./2.0)-Q_swingup3_2./2.0+lambda4.*(b1.*m_pend.*r_com_pend.*t3.*t24+b1.*m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t27.*2.0)+lambda3.*t2.*t3.*t4.*t6.*t27.*t58.*2.0,-Q_swingup3_3,t81,0.0,1.0,t24.*t61,-t24.*t64,t75,Q_swingup2_4.*(-1.0./2.0)-Q_swingup4_2./2.0+lambda3.*(m_pend.*r_com_pend.*t24.*t79-t2.*t3.*t4.*t6.*t27.*t61.*2.0)-lambda4.*(dtheta_pend.*t2.*t4.*t24.*t51.*4.0-t2.*t3.*t4.*t6.*t27.*t64.*2.0),t81,-Q_swingup4_4-lambda3.*m_pend.*r_com_pend.*t24.*(I_pend.*t3.*4.0+m_pend.*t2.*t3.*4.0)-lambda4.*t2.*t4.*t24.*t82.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-t24.*(I_pend.*t12.*t15.*t26+m_pend.*t2.*t12.*t15.*t26),-m_pend.*r_com_pend.*t6.*t12.*t15.*t24.*t26,0.0,lambda4.*(m_pend.*r_com_pend.*t3.*t12.*t15.*t24.*t26+m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t12.*t26.*t39.*2.0)+m_pend.*r_com_pend.*t24.*t69+t2.*t3.*t4.*t6.*t27.*t45.*2.0+lambda3.*t2.*t3.*t4.*t6.*t12.*t26.^2.*t39.*2.0+t2.*t3.*t4.*t6.*t12.*t20.*t26.*t39.*2.0,b1.*t24.*t26,-m_pend.*r_com_pend.*t24.*t85,0.0,0.0,-t24.*(r_com_pend.*t2.*t4.*t6.*t12.*t15+I_pend.*m_pend.*r_com_pend.*t6.*t12.*t15),-t2.*t4.*t11.*t12.*t15.*t24,0.0,lambda4.*(t2.*t3.*t4.*t6.*t12.*t15.*t24+t3.*t6.*t11.*t12.*t37.*t39.*t40.*2.0)-m_pend.*r_com_pend.*t24.*t73+t2.*t3.*t4.*t6.*t27.*t34.*2.0+m_pend.*r_com_pend.*t3.*t12.*t15.*t20.*t24+m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t12.*t20.*t39.*2.0+lambda3.*m_pend.*r_com_pend.*t2.*t3.*t4.*t11.*t12.*t26.*t39.*2.0,b1.*m_pend.*r_com_pend.*t6.*t24,t24.*t86],[8,8]);
