function u_PMP = autogen_control_PMP(I_pend,R_swingup1,lambda3,lambda4,m_cart,m_pend,r_com_pend,theta_pend)
%AUTOGEN_CONTROL_PMP
%    U_PMP = AUTOGEN_CONTROL_PMP(I_PEND,R_SWINGUP1,LAMBDA3,LAMBDA4,M_CART,M_PEND,R_COM_PEND,THETA_PEND)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Apr-2020 22:51:49

t2 = r_com_pend.^2;
t3 = m_pend.^2;
t4 = sin(theta_pend);
u_PMP = -(I_pend.*lambda3+lambda3.*m_pend.*t2+lambda4.*m_pend.*r_com_pend.*t4)./(I_pend.*R_swingup1.*m_cart+I_pend.*R_swingup1.*m_pend+R_swingup1.*t2.*t3+R_swingup1.*m_cart.*m_pend.*t2-R_swingup1.*t2.*t3.*t4.^2);
